export const recipeMock = [

  {
    id: 1,
    name: 'Recipe 1 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 2,
    name: 'Recipe 2 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 3,
    name: 'Recipe 3 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 4,
    name: 'Recipe 4 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 5,
    name: 'Recipe 5 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 6,
    name: 'Recipe 6 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 7,
    name: 'Recipe 7 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 8,
    name: 'Recipe 8 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 9,
    name: 'Recipe 9 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 10,
    name: 'Recipe 10 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 11,
    name: 'Recipe 11 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 12,
    name: 'Recipe 12 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 13,
    name: 'Recipe 13 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 14,
    name: 'Recipe 14 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 15,
    name: 'Recipe 14 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 16,
    name: 'Recipe 16 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing2141', 'ing3', 'ing2'],
  },
  {
    id: 17,
    name: 'Recipe 17 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 18,
    name: 'Recipe 18 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1510', 'ing3', 'ing2'],
  },
  {
    id: 19,
    name: 'Recipe 19 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing21211', 'ing3', 'ing2'],
  },
  {
    id: 20,
    name: 'Recipe 20 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing541', 'ing354', 'ing2'],
  },
  {
    id: 21,
    name: 'Recipe 21 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing541', 'ing54553', 'ing2'],
  },
  {
    id: 22,
    name: 'Recipe 22 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 23,
    name: 'Recipe 23 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing155', 'ing35', 'ing2'],
  },
  {
    id: 24,
    name: 'Recipe 24 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing541', 'ing3', 'ing22'],
  },
  {
    id: 25,
    name: 'Recipe 25 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 26,
    name: 'Recipe 26 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 27,
    name: 'Recipe 27 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 28,
    name: 'Recipe 28 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 29,
    name: 'Recipe 29 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 30,
    name: 'Recipe 30 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 31,
    name: 'Recipe 31 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 32,
    name: 'Recipe 32 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 33,
    name: 'Recipe 33 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 34,
    name: 'Recipe 34 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 35,
    name: 'Recipe 34 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 36,
    name: 'Recipe 36 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 37,
    name: 'Recipe 37 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 38,
    name: 'Recipe 38 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 39,
    name: 'Recipe 39 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
  {
    id: 40,
    name: 'Recipe 40 ',
    text: 'this a plain test for test purposes',
    ingredients: ['ing1', 'ing3', 'ing2'],
  },
];
